### ISSUE TITLE
[Feature] REST APIs of Store Domain

### ISSUE THREAD

**Issue by himodu** [9roomthonUniv-MyMoo/MyMoo-BackEnd#4]
## Work Details
- get All Stores
- get One Store
- get By Any Condition
- patch visitCount, usableDonation

## Task List
- [ ] get All Stores
- [ ] get One Store
- [ ] get By Any Condition
- [ ] patch visitCount, usableDonation
